version: '3'

services:
  nginx:
    build: data/nginx
    image: tabletennis/nginx
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
     - 443:443

  app:
    build:
      context: .
      args:
        DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    image: tabletennis/app
    container_name: tabletennis
    restart: unless-stopped
    hostname: app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB

